---
# tasks file for postgresql
- name: Install postgresql
  package:
    name: "{{postgresql_package[ansible_os_family]}}"
    state: present

- name: Initial cluster setup
  command: "{{postgresql_cluster_init['v' ~ ansible_distribution_major_version]}}"
  args:
    warn: false
    creates: /var/lib/pgsql/data/postgresql.conf
  when: ansible_os_family == 'RedHat'

- name: Configure service
  service: name=postgresql enabled=yes state=started
