---
# tasks file for postgresql
- name: Install postgresql
  package:
    name: "{{ postgresql_packages }}"
    state: present

- include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Create conf.d
  file:
    path: "{{ postgresql_extra_config_dir }}"
    state: directory
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
  become: true

- name: Set conf.d include in postgresql.conf
  lineinfile: line="include_dir 'conf.d'" dest="{{ postgresql_config_file }}"
  when: postgresql_version is version_compare('9.3', '>=')

- name: Include 25_ansible.conf in postgresql.conf
  lineinfile: line="include 'conf.d/25_ansible.conf'" dest="{{ postgresql_config_file }}"
  when: postgresql_version is version_compare('9.3', '<')

- name: Create configuration file
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_extra_config_file }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
  notify: restart postgresql

- name: Add custom entries to pg_hba.conf
  blockinfile:
    path: "{{ postgresql_pg_hba_conf_file }}"
    block: "{{ postgresql_pg_hba_config | join('\n')  }}"
  when: postgresql_pg_hba_config is defined

- name: Add custom entries to pg_ident.conf
  blockinfile:
    path: "{{ postgresql_pg_ident_conf_file }}"
    block: "{{ postgresql_pg_ident_config | join('\n')  }}"
  when: postgresql_pg_ident_config is defined

- name: Enable and start postgresql service
  service:
    name: "{{ postgresql_service }}"
    enabled: true
    state: started
