---
# tasks file for postgresql
- name: Install postgresql
  package:
    name: "{{postgresql_packages}}"
    state: present

- include_tasks: "{{ansible_os_family | lower}}.yml"

- name: Enable and start postgresql service
  service:
    name: "{{postgresql_service}}"
    enabled: true
    state: started
