---
# tasks file for postgresql (RedHat)

- name: Get installed version
  shell: rpm --query "{{ postgresql_package }}" --queryformat "%{version}"
  args:
    warn: false
  register: postgresql_version_query
  when: postgresql_version is undefined
  check_mode: false
  changed_when: false

- name: Set version fact
  set_fact:
    postgresql_version: "{{ postgresql_version_query.stdout }}"
  when: postgresql_version is undefined

- name: Initial cluster setup
  command: "{{ postgresql_cluster_init[ansible_os_family]['v' ~ ansible_distribution_major_version] }}"
  args:
    creates: "{{ postgresql_config_file }}"
    warn: false
