---
- name: Converge
  hosts: all

  vars:
    postgresql_config:
      max_connections: 50
      listen_addresses: "'*'"
    postgresql_pg_hba_config:
      - "host all all 127.0.0.1/32 password"
      - "host all all 127.0.0.1/32 md5"
    postgresql_pg_ident_config:
      - "bithium   /^(.*)@bithium\\.com$      \\1"
      - "bithium   /^(.*)@example\\.com$    guest"

  vars_files:
    - goss.yml

  roles:
    - role: postgresql

  tasks:
    - name: Dump host variables for role
      template: src=config.yml.j2 dest={{ goss_test_variables }}
