---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: postgresql-alpine-3.11
    image: alpine:3.11
    volumes:
      - "/mnt/mirrors/alpine/3.11:/var/cache/apk"
    command: /sbin/init
  - name: postgresql-alpine-3.12
    image: alpine:3.12
    volumes:
      - "/mnt/mirrors/alpine/3.12:/var/cache/apk"
    command: /sbin/init
  - name: postgresql-centos-7
    image: centos:7
    volumes:
      - "/mnt/mirrors/centos/7:/var/cache/yum"
    command: /sbin/init
  - name: postgresql-centos-8
    image: centos:8
    volumes:
      - "/mnt/mirrors/centos/8:/var/cache/yum"
    command: /sbin/init
  - name: postgresql-debian-stable
    image: debian:stable
    volumes:
      - "/mnt/mirrors/debian/stable:/var/cache/apt/archives"
    command: /lib/systemd/systemd
  - name: postgresql-ubuntu-18.04
    image: ubuntu:18.04
    volumes:
      - "/mnt/mirrors/ubuntu/18.04:/var/cache/apt/archives"
    command: /sbin/init
  - name: postgresql-ubuntu-20.04
    image: ubuntu:20.04
    volumes:
      - "/mnt/mirrors/ubuntu/20.04:/var/cache/apt/archives"
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  # log: True
  config_options:
    defaults:
      interpreter_python: "/usr/bin/python3"
  inventory:
    host_vars:
      postgresql-centos-7:
        ansible_python_interpreter: "/usr/bin/python"
  lint: |
    set -e
    yamllint .
    ansible-lint
    flake8
scenario:
  name: default
