---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: postgresql-centos-6
    image: centos:6
    volume_mounts:
      - "/mnt/mirrors/centos/7:/var/cache/yum"
  - name: postgresql-centos-7
    image: centos:7
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/mnt/mirrors/centos/7:/var/cache/yum"
    command: "/usr/sbin/init"
  - name: postgresql-ubuntu-14.04
    image: ubuntu:14.04
    volumes:
      - "/mnt/mirrors/ubuntu/14.04:/var/cache/apt/archives"
  - name: postgresql-ubuntu-16.04
    image: ubuntu:16.04
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/mnt/mirrors/ubuntu/16.04:/var/cache/apt/archives"
    command: "/sbin/init"
  - name: postgresql-ubuntu-18.04
    image: ubuntu:18.04
    volumes:
      - "/mnt/mirrors/ubuntu/18.04:/var/cache/apt/archives"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
    enabled: false
