---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Configure Alpine openrc
      script: ./alpine.sh
      when: ansible_os_family == 'Alpine'

    - name: Setup local package cache
      file:
        src: /var/cache/apk
        dest: /etc/apk/cache
        state: link
      when: ansible_os_family == 'Alpine'

    - name: Restart the container
      local_action: docker_container
      args:
        name: "{{ansible_nodename}}"
        state: started
        restart: true
      when: ansible_os_family == 'Alpine'
